version: '3'
services:

  zookeeper:
    image: 'bitnami/zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  consumer:
    image: "consumer:1.0"
    ports:
      - "9000:8080"

  producer:
    image: "producer:1.0"
    ports:
      - "9100:8080"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local